import type { Meal } from "@/lib/types";

export const initialMeals: Meal[] = [
  {
    id: "nigeria-akara-pap",
    name: "Akara and Pap",
    description: "Crispy bean cakes with warm corn pap for a classic morning boost.",
    country: "Nigeria",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/HERU9eJwYvQ",
    ingredients: ["Black-eyed beans", "Onion", "Pepper", "Salt", "Vegetable oil", "Corn pap"],
    cookingSteps: ["Peel and blend beans with onion and pepper.", "Whisk with salt until light.", "Scoop into hot oil and fry until golden.", "Serve with warm pap."],
    cookingTime: "25 min",
    difficulty: "Medium",
    tags: ["cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "nigeria-yam-egg",
    name: "Yam and Egg Sauce",
    description: "Soft boiled yam with bright tomato egg sauce.",
    country: "Nigeria",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/jXhTZfIGp_o",
    ingredients: ["Yam", "Eggs", "Tomatoes", "Onion", "Pepper", "Oil"],
    cookingSteps: ["Boil yam with salt until tender.", "Saute onion, tomato, and pepper.", "Add eggs and stir softly.", "Plate with the yam."],
    cookingTime: "30 min",
    difficulty: "Easy",
    tags: ["quick", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "nigeria-moi-moi",
    name: "Moi Moi Cups",
    description: "Steamed bean pudding cups packed with peppery flavor.",
    country: "Nigeria",
    mealType: "lunch",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/v93s7xnY9fY",
    ingredients: ["Beans", "Red pepper", "Onion", "Palm oil", "Seasoning", "Boiled egg"],
    cookingSteps: ["Blend peeled beans with peppers and onion.", "Mix in oil and seasoning.", "Pour into cups with egg pieces.", "Steam until set."],
    cookingTime: "50 min",
    difficulty: "Medium",
    tags: ["healthy", "cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "nigeria-jollof",
    name: "Party Jollof Bowl",
    description: "Smoky tomato rice with vegetables and a happy spoonful of spice.",
    country: "Nigeria",
    mealType: "dinner",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/EfZEArZcfAY",
    ingredients: ["Rice", "Tomato stew", "Stock", "Onion", "Thyme", "Bay leaf"],
    cookingSteps: ["Cook tomato stew until reduced.", "Add stock and spices.", "Stir in washed rice.", "Steam on low until fluffy."],
    cookingTime: "55 min",
    difficulty: "Medium",
    tags: ["local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "uk-porridge",
    name: "Berry Porridge",
    description: "Creamy oats with berries and a drizzle of honey.",
    country: "United Kingdom",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/ywkEGKXk2cQ",
    ingredients: ["Oats", "Milk", "Berries", "Honey", "Pinch of salt"],
    cookingSteps: ["Simmer oats, milk, and salt.", "Stir until creamy.", "Top with berries and honey.", "Serve warm."],
    cookingTime: "10 min",
    difficulty: "Easy",
    tags: ["quick", "healthy", "cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "uk-beans-toast",
    name: "Beans on Toast",
    description: "Toasty bread with warm beans for a fast comfort bite.",
    country: "United Kingdom",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/wVIhQ9d2L9w",
    ingredients: ["Bread", "Baked beans", "Butter", "Black pepper", "Cheddar"],
    cookingSteps: ["Toast the bread.", "Warm the beans.", "Butter toast and spoon beans over it.", "Finish with pepper and cheese."],
    cookingTime: "8 min",
    difficulty: "Easy",
    tags: ["quick", "cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "uk-jacket-potato",
    name: "Tuna Jacket Potato",
    description: "A fluffy baked potato with tuna, sweetcorn, and yogurt.",
    country: "United Kingdom",
    mealType: "lunch",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/vxQDD8mxk2c",
    ingredients: ["Potato", "Tuna", "Sweetcorn", "Greek yogurt", "Chives"],
    cookingSteps: ["Bake or microwave the potato.", "Mix tuna, corn, and yogurt.", "Split potato open.", "Fill and top with chives."],
    cookingTime: "20 min",
    difficulty: "Easy",
    tags: ["healthy", "cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "brazil-acai",
    name: "Acai Banana Bowl",
    description: "A chilled acai bowl with banana, granola, and berries.",
    country: "Brazil",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/mN-fX2k8rZg",
    ingredients: ["Acai puree", "Banana", "Granola", "Berries", "Honey"],
    cookingSteps: ["Blend acai and banana until thick.", "Spoon into a bowl.", "Top with granola and fruit.", "Drizzle honey."],
    cookingTime: "7 min",
    difficulty: "Easy",
    tags: ["quick", "healthy", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "brazil-pao-queijo",
    name: "Pao de Queijo",
    description: "Chewy cheese bread bites that vanish fast.",
    country: "Brazil",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/e1cN2vc1a2A",
    ingredients: ["Tapioca flour", "Milk", "Oil", "Eggs", "Cheese", "Salt"],
    cookingSteps: ["Warm milk and oil.", "Mix into tapioca flour.", "Beat in eggs and cheese.", "Bake until puffed."],
    cookingTime: "35 min",
    difficulty: "Medium",
    tags: ["local", "cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "brazil-feijoada-lite",
    name: "Feijoada Lite",
    description: "A simple black bean bowl with rice and orange slices.",
    country: "Brazil",
    mealType: "dinner",
    imageUrl: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/x9N0d9oTxHk",
    ingredients: ["Black beans", "Rice", "Garlic", "Onion", "Smoked paprika", "Orange"],
    cookingSteps: ["Saute garlic and onion.", "Add beans and paprika.", "Simmer until glossy.", "Serve with rice and orange."],
    cookingTime: "40 min",
    difficulty: "Easy",
    tags: ["healthy", "cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "us-avocado-toast",
    name: "Avocado Egg Toast",
    description: "Crunchy toast, creamy avocado, and a sunny egg.",
    country: "United States",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/Wmo1NoYEFPw",
    ingredients: ["Bread", "Avocado", "Egg", "Lime", "Chilli flakes", "Salt"],
    cookingSteps: ["Toast bread.", "Mash avocado with lime and salt.", "Cook egg to preference.", "Layer and sprinkle chilli."],
    cookingTime: "12 min",
    difficulty: "Easy",
    tags: ["quick", "healthy"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "us-pancakes",
    name: "Mini Pancake Stack",
    description: "Small fluffy pancakes with fruit and maple syrup.",
    country: "United States",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/FLd00Bx4tOk",
    ingredients: ["Flour", "Egg", "Milk", "Baking powder", "Maple syrup", "Fruit"],
    cookingSteps: ["Whisk batter.", "Cook small rounds on a pan.", "Flip when bubbles appear.", "Stack with fruit and syrup."],
    cookingTime: "20 min",
    difficulty: "Easy",
    tags: ["cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "us-turkey-wrap",
    name: "Turkey Crunch Wrap",
    description: "A crisp wrap with turkey, greens, and yogurt ranch.",
    country: "United States",
    mealType: "lunch",
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/5qk9vS6nZrs",
    ingredients: ["Tortilla", "Turkey", "Lettuce", "Tomato", "Greek yogurt", "Herbs"],
    cookingSteps: ["Mix yogurt and herbs.", "Layer tortilla with turkey and vegetables.", "Drizzle sauce.", "Roll tightly and slice."],
    cookingTime: "10 min",
    difficulty: "Easy",
    tags: ["quick", "healthy"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "india-poha",
    name: "Lemon Poha",
    description: "Flattened rice tossed with peanuts, turmeric, and lemon.",
    country: "India",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/h8J0Q3hRzUI",
    ingredients: ["Poha", "Peanuts", "Onion", "Turmeric", "Mustard seeds", "Lemon"],
    cookingSteps: ["Rinse poha briefly.", "Toast peanuts and spices.", "Cook onion with turmeric.", "Fold in poha and lemon."],
    cookingTime: "15 min",
    difficulty: "Easy",
    tags: ["quick", "cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "india-masala-omelette",
    name: "Masala Omelette",
    description: "Eggs with onion, chilli, tomato, and coriander.",
    country: "India",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/qXPhVYpQLPA",
    ingredients: ["Eggs", "Onion", "Tomato", "Green chilli", "Coriander", "Salt"],
    cookingSteps: ["Beat eggs with chopped vegetables.", "Heat a little oil.", "Pour mixture into pan.", "Cook both sides until set."],
    cookingTime: "10 min",
    difficulty: "Easy",
    tags: ["quick", "cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "ghana-hausa-koko",
    name: "Hausa Koko",
    description: "Spiced millet porridge with roasted peanuts.",
    country: "Ghana",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/eu0cZs5jD1A",
    ingredients: ["Millet flour", "Ginger", "Cloves", "Sugar", "Water", "Peanuts"],
    cookingSteps: ["Mix millet flour with water.", "Boil spiced water.", "Whisk in millet mix.", "Serve with peanuts."],
    cookingTime: "18 min",
    difficulty: "Easy",
    tags: ["cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "ghana-waakye",
    name: "Waakye Bowl",
    description: "Rice and beans with egg, stew, and crunchy salad.",
    country: "Ghana",
    mealType: "lunch",
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/dVzNn3L2oKQ",
    ingredients: ["Rice", "Beans", "Egg", "Tomato stew", "Cabbage", "Shito"],
    cookingSteps: ["Cook beans until soft.", "Add rice and cook together.", "Boil egg and slice salad.", "Serve with stew and shito."],
    cookingTime: "55 min",
    difficulty: "Medium",
    tags: ["cheap", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "other-shakshuka",
    name: "Shakshuka Skillet",
    description: "Eggs simmered in tomato pepper sauce with herbs.",
    country: "Other",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/ifWWRZSWS18",
    ingredients: ["Eggs", "Tomatoes", "Bell pepper", "Onion", "Paprika", "Parsley"],
    cookingSteps: ["Cook onion and pepper.", "Add tomatoes and paprika.", "Make wells and crack eggs in.", "Cover until eggs set."],
    cookingTime: "25 min",
    difficulty: "Easy",
    tags: ["healthy", "cheap"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "other-greek-yogurt",
    name: "Greek Yogurt Crunch",
    description: "Yogurt, fruit, nuts, and granola in one bright bowl.",
    country: "Other",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/ZkjX5o_8K6M",
    ingredients: ["Greek yogurt", "Granola", "Banana", "Berries", "Nuts", "Honey"],
    cookingSteps: ["Spoon yogurt into a bowl.", "Add sliced fruit.", "Sprinkle granola and nuts.", "Finish with honey."],
    cookingTime: "5 min",
    difficulty: "Easy",
    tags: ["quick", "healthy"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "other-veggie-noodles",
    name: "Veggie Noodle Stir Fry",
    description: "Fast noodles with crisp vegetables and soy ginger sauce.",
    country: "Other",
    mealType: "dinner",
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/aA0G6x8xwBQ",
    ingredients: ["Noodles", "Carrot", "Cabbage", "Soy sauce", "Ginger", "Sesame oil"],
    cookingSteps: ["Cook noodles.", "Stir fry vegetables.", "Add ginger and soy sauce.", "Toss noodles through."],
    cookingTime: "18 min",
    difficulty: "Easy",
    tags: ["quick", "cheap", "healthy"],
    createdAt: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "brazil-tapioca-crepe",
    name: "Tapioca Breakfast Crepe",
    description: "A naturally gluten-free tapioca crepe filled with cheese and tomato.",
    country: "Brazil",
    mealType: "breakfast",
    imageUrl: "https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=1200&q=80",
    videoUrl: "https://www.youtube.com/embed/8BVmN15F6mc",
    ingredients: ["Tapioca starch", "Cheese", "Tomato", "Oregano", "Salt"],
    cookingSteps: ["Sift tapioca starch into a dry pan.", "Cook until it forms a crepe.", "Add cheese and tomato.", "Fold and warm through."],
    cookingTime: "12 min",
    difficulty: "Easy",
    tags: ["quick", "local"],
    createdAt: "2026-01-01T00:00:00.000Z"
  }
];
